### ISSUE TITLE
Return code 256; Key error: 'STEAM_COMPAT_CLIENT_INSTALL_PATH'

### ISSUE THREAD

**Issue by astorioth** [rockerbacon/lutris-skyrimse-installers#229]
Hi, I'm trying to get a bottle of MO2 to work on SSE to no avail. I know that the proton on the runner is the 5.0, but my SSE won't run on 5.0 at all, so I edited the runner to read the 6.3 version instead. Now, my game runs, but MO2 won't start at all-- though it at least has an error now. I searched for this error (256) and I read on one of the threads here about a strace problem, but I'm not sure if that applies to my problem.

Any help would be appreciated.

```
Running /home/lyalith/Games/mod-organizer-2/run.sh
Initial process has started with pid 12099
Start monitoring process.
Searching for Steam in '/home/lyalith/.steam/debian-installation'
Found Steam
Searching for Steam in '/home/lyalith/.var/app/com.valvesoftware.Steam/.local/share/Steam'
Searching for game in library '/home/lyalith/.steam/debian-installation'
Found game
Searching for 'Proton 6.3' in library '/home/lyalith/.steam/debian-installation'
Found Proton
WARN: could not find Steam runtime, you might experience problems


	PATH='/home/lyalith/.steam/debian-installation/ubuntu12_32/steam-runtime/amd64/usr/bin:/home/lyalith/.steam/debian-installation/ubuntu12_32/steam-runtime/usr/bin:/home/lyalith/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin' \
	LD_LIBRARY_PATH='/usr/lib/x86_64-linux-gnu/libfakeroot:/lib/i386-linux-gnu/sse2:/lib/i386-linux-gnu/i686/sse2:/lib:/lib/i386-linux-gnu:/lib/x86_64-linux-gnu:/lib64:/usr/lib:/usr/lib64:/usr/lib32:/usr/lib64:/usr/lib/i386-linux-gnu:/usr/lib/x86_64-linux-gnu:/home/lyalith/.local/share/lutris/runtime/Ubuntu-18.04-i686:/home/lyalith/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/lyalith/.local/share/lutris/runtime/steam/i386/lib:/home/lyalith/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/lyalith/.local/share/lutris/runtime/steam/i386/usr/lib:/home/lyalith/.local/share/lutris/runtime/Ubuntu-18.04-x86_64:/home/lyalith/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/lyalith/.local/share/lutris/runtime/steam/amd64/lib:/home/lyalith/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/lyalith/.local/share/lutris/runtime/steam/amd64/usr/lib:$LD_LIBRARY_PATH' \
	STEAM_COMPAT_DATA_PATH='/home/lyalith/.steam/debian-installation/steamapps/compatdata/489830' \
	SteamGameId=489830 \
	SteamAppId=489830 \
	WINEDLLOVERRIDES='xaudio2_7=n,b;' PULSE_LATENCY_MSEC=90 \
	\
	'/home/lyalith/.steam/debian-installation/steamapps/common/Proton 6.3/proton' run '/home/lyalith/Games/mod-organizer-2/ModOrganizer2/ModOrganizer.exe' 


Traceback (most recent call last):
  File "/home/lyalith/.steam/debian-installation/steamapps/common/Proton 6.3/proton", line 1031, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/lyalith/.steam/debian-installation/steamapps/common/Proton 6.3/proton", line 860, in init_session
    g_compatdata.setup_prefix()
  File "/home/lyalith/.steam/debian-installation/steamapps/common/Proton 6.3/proton", line 483, in setup_prefix
    steamdir = os.environ["STEAM_COMPAT_CLIENT_INSTALL_PATH"]
  File "/usr/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'STEAM_COMPAT_CLIENT_INSTALL_PATH'
Monitored process exited.
Initial process has exited (return code: 256)
All children have exited.
Exit with returncode 256
```

**Comment by Markaos** [comment]
Workaround:

Open `~/.local/share/modorganizer2/proton-launcher.sh` and scroll to the bottom. You should see this near bottom:

```
run_proton="
	PATH='$steam_rundir/amd64/usr/bin:$steam_rundir/usr/bin:$PATH' \\
	LD_LIBRARY_PATH='$library_path' \\
	STEAM_COMPAT_DATA_PATH='$compat_data' \\
	SteamGameId=$appid \\
	SteamAppId=$appid \\
	${proton_extra_envs[*]} \\
	\\
	'$proton_dir/proton' run '$executable' $([ -n "$1" ] && printf " '%s'" "$@")
"
```

Add line `STEAM_COMPAT_CLIENT_INSTALL_PATH='$steam_dir' \\` for example after `STEAM_COMPAT_DATA_PATH='$compat_data' \\` and you should be good to go.
